# Generated by Django 3.0.7 on 2020-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(help_text="Commonly known as 'first name' in the US.", max_length=32)),
                ('family_name', models.CharField(help_text="Commonly known as 'last name' in the US.", max_length=32)),
                ('talk_title', models.CharField(max_length=64)),
                ('contact_email', models.EmailField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, help_text='This is optional. Leave the field blank, or enter your handle without the @ symbol.', max_length=32, null=True)),
            ],
        ),
    ]
